apiVersion: v1
kind: Service
metadata:
  name: api

spec: 
  selector: 
    app: api
    app: api
# type: NodePort

  ports:
    - port: 80
      targetPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: tag_checker

spec:
  selector:
    name: tag_checker
    app: worker

  ports:
    - port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: content_writer

spec:
  selector:
    name: content_writer
    app: worker
    
  ports:
    - port: 5000
      targetPort: 5000


---


apiVersion: v1
kind: Service
metadata:
  name: content_reader

spec:
  selector:
    name: content_reader
    app: worker

  ports:
    - port: 5000
      targetPort: 5000


---


apiVersion: v1
kind: Service
metadata:
  name: link_creator

spec:
  selector:
    name: link_creator
    app: bot

  ports:
    - port: 5000
      targetPort: 5000


---


apiVersion: v1
kind: Service
metadata:
  name: sign_in

spec: 
  selector:
    name: sign_in
    app: bot

  ports: 
    - port: 5000
      targetPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: article_creator

spec:
  selector:
    name: article_creator
    app: bot
  
  ports:
    - port: 5000
      targetPort: 5000


---


apiVersion: v1
kind: Service
metadata:
  name: chrome

spec: 
  selector:
    name: chrome
    app: bot

  ports:
    - port: 4444
      targetPort: 4444

